baseURL = 'https://wiki.hilldir.fr/'
locale = 'fr-fr'
title = 'Hildir | Wiki'
enableEmoji = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.footer]
copyright = "© Hildir - 2026"
version = true

[params.social]
github = "HildirMc/HildirMc.github.io"

[params.docs]
themeColor = "emerald"
darkMode = true
logoLinkURL = "https://hildir.fr"
sidebarIcons = true
titleIcon = true
repoURL = "https://github.com/HildirMc/HildirMc.github.io"
lastMod = true